export const ARCHIVE_FORM_LABELS = {
    title: "Modmail Archiver Settings",
    acceptLabel: "Run Archiver",
    cancelLabel: "Cancel",
    archiverNoHighlighteds: "Skip Highlighted Conversations?",
    archiveLastReplyUser: "Archive - Last Reply By User (hours)",
    archiveLastReplyMod: "Archive - Last Reply By Mod (hours)",
    archiveAutoGenerated: "Archive - Auto-Generated With No Replies (hours)",
};

export const ARCHIVE_FORM_HELP_TEXTS = {
    title: "Once you hit run, modmail conversations will be archived based on the settings below.",
    archiverNoHighlighteds: "If this setting is enabled, highlighted conversations will not be archived.",
    archiveLastReplyUser: "If the last reply to a conversation was by a user, it will only be archived if their reply was this many hours ago.",
    archiveLastReplyMod: "If the last reply to a conversation was by a moderator, it will only be archived if the mod reply was this many hours ago.",
    archiveAutoGenerated: "If an auto-generated conversation has no mod replies, it will be archived if it's older than this many hours.",
};
