
export const SETTING_DEFAULTS = {
    highlighterEnabled: true,
    highlighterAdmins: true,
    highlighterContributors: false,
    highlighterNoSents: true,
    highlighterNoAutoGens: false,
    highlighterUsernames: "ModmailAssistant,AnotherUser,YetAnotherUser,AndSoOn",
    highlighterFlairs: "priority",
    highlighterSubreddits: false,
    archiverEnabled: false,
    archiverNoHighlighteds: true,
    archiveLastReplyMod: 24,
    archiveAutoGenerated: 720,
    archiveLastReplyUser: 720,
    modmailMentionsEnabled: true,
    modmailMentionsOnlyMods: true,
    modmailMentionsOnlyOnce: false,
};
