
export const SETTING_DEFAULTS = {
    highlighterEnabled: true,
    highlighterAdmins: true,
    highlighterContributors: false,
    highlighterNoSents: true,
    highlighterNoAutoGens: false,
    highlighterUsernames: "ModmailAssistant,AnotherUser,YetAnotherUser,AndSoOn",
    highlighterFlairs: "f3b3ba72-5bbc-11ee-8d00-fe02b9c3631d,94652820-0711-11ef-bd8e-ba4803bace8a",
    highlighterSubreddits: false,
    archiverEnabled: false,
    archiverNoHighlighteds: true,
    archiveLastReplyMod: 24,
    archiveAutoGenerated: 720,
    archiveLastReplyUser: 720,
    modmailMentionsEnabled: true,
    modmailMentionsOnlyMods: true,
    modmailMentionsOnlyOnce: false,
};
