import {Devvit} from "@devvit/public-api";
import {DEFAULTS, HELP_TEXTS, LABELS} from "./constants.js";
import {onModMail} from "./handlers/triggers.js";
import {validateUsernameList} from "devvit-helpers";

// Enable any Devvit features you might need.
Devvit.configure({
    redditAPI: true,
});

// Set up the configuration field presented to the user for each installation (subreddit) of the app.
Devvit.addSettings([
    {
        type: "string",
        name: "usernames",
        label: LABELS.USERNAMES,
        helpText: HELP_TEXTS.USERNAMES,
        defaultValue: DEFAULTS.USERNAMES,
        onValidate: validateUsernameList,
    },
    {
        type: "boolean",
        name: "admins",
        label: LABELS.ADMINS,
        helpText: HELP_TEXTS.ADMINS,
        defaultValue: DEFAULTS.ADMINS,
    },
    {
        type: "boolean",
        name: "subreddits",
        label: LABELS.SUBREDDITS,
        helpText: HELP_TEXTS.SUBREDDITS,
        defaultValue: DEFAULTS.SUBREDDITS,
    },
    {
        type: "boolean",
        name: "contributors",
        label: LABELS.CONTRIBUTORS,
        helpText: HELP_TEXTS.CONTRIBUTORS,
        defaultValue: DEFAULTS.CONTRIBUTORS,
    },
    {
        type: "boolean",
        name: "sent",
        label: LABELS.SENT,
        helpText: HELP_TEXTS.SENT,
        defaultValue: DEFAULTS.SENT,
    },
    {
        type: "boolean",
        name: "autoGenerated",
        label: LABELS.AUTOGEN,
        helpText: HELP_TEXTS.AUTOGEN,
        defaultValue: DEFAULTS.AUTOGEN,
    },
]);

Devvit.addTrigger({
    event: "ModMail",
    onEvent: onModMail,
});

export default Devvit;
